### PR TITLE
Start glusterd if not already started

### PR DESCRIPTION
**Pull request by sac**

### CODE REVIEW

**Comment by mykaul** [comment]
Do we also need to enable it? (I did not check if it is)

**Comment by sac** [comment]
> Do we also need to enable it? (I did not check if it is)

It is highly likely that it is not enabled. I will add that, my mistake.

**Comment by sac** [comment]
> > Do we also need to enable it? (I did not check if it is)
> 
> It is highly likely that it is not enabled. I will add that, my mistake.

Updated the patch.

**Review by parthdhanjal — APPROVED** [review]

**Comment by sac** [comment]
Thanks @parthdhanjal

**Pull request merged**
